/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#ffffff',
        foreground: '#171717',
        'brand-blue': '#003399',
        'brand-green': '#739400',
        'brand-gray': '#737986',
        'text-black': '#0E1013',
        'text-white': '#FCFDFF',
        'text-blue': '#003399',
        'blue-shadow1': '#001847',
        'blue-shadow2': '#002570',
        'blue-shadow3': '#003399',
        'blue-shadow4': '#134EC2',
        'blue-shadow5': '#2F6DEB',
        'blue-shadow6': '#588FFF',
        'blue-shadow7': '#7CA8FF',
        'blue-shadow8': '#A1C0FF',
        'blue-shadow9': '#C6D9FF',
        'blue-shadow10': '#EAF1FF',
        'green-shadow1': '#536B00',
        'green-shadow2': '#739400',
        'green-shadow3': '#97BD13',
        'green-shadow4': '#BDE62E',
        'green-shadow5': '#D7FF4D',
        'green-shadow6': '#DEFF6D',
        'green-shadow7': '#E5FF8D',
        'green-shadow8': '#EDFFAD',
        'green-shadow9': '#F4FFCD',
        'green-shadow10': '#FBFFED',
        'gray-shadow1': '#353942',
        'gray-shadow2': '#494E59',
        'gray-shadow3': '#5D636F',
        'gray-shadow4': '#737986',
        'gray-shadow5': '#89909D',
        'gray-shadow6': '#A0A7B3',
        'gray-shadow7': '#B8BECA',
        'gray-shadow8': '#D0D6E1',
        'gray-shadow9': '#EAEFF7',
        'gray-shadow10': '#F8F9FA',
        'background-1': '#F8F8F8',
        'gray-border': '#D9D9D9',
        'text-gray': '#757575',
        'error': '#F41F17',
        'error-hover': '#F50A06',
        'success': '#11B364',
      },
      fontFamily: {
        sans: ['Montserrat', 'Arial', 'Helvetica', 'sans-serif'],
      },
      fontSize: {
        '5xl': ['65px', '1'],
        '4xl': ['49px', '1'],
        '3xl': ['39px', '1'],
        '2xl': ['31px', '1'],
        xl: ['25px', '1'],
        lg: ['20px', '1'],
        base: ['16px', '1'],
        sm: ['13px', '1'],
        xs: ['10px', '1'],
      },
    },
  },
  plugins: [],
};
